export const GET_ALL_QUESTIONS = "GET_ALL_QUESTIONS";
export const GET_USERS = "GET_USERS";
export const SAVE_NEW_POLL_QUESTION = "SAVE_NEW_POLL_QUESTION";
export const UPDATE_USER_ANSWER = "UPDATE_USER_ANSWER";
export const UPDATE_QUESTION_ANSWER = "UPDATE_QUESTION_ANSWER";
